name: Iter
version: '0.0.1'
main: me.antidotaleks.iter.Iter
api-version: '1.21'
authors: [AntidotAleks]
depend:
  - ProtocolLib
commands:
  iqueue:
    description: Start a queue.
    usage: /iqueue
  iteam:
    description: Join a team.
    usage: /iteam <invite|kick|join|accept|decline|leave|list> [player]
  itest:
    description: Test command.
    usage: /itest
    permission: iter.itest